# Generated by Django 2.2.6 on 2020-01-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='areyou',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Job seeker', 'Job seeker')], default='job seeker', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='profilepics/'),
        ),
    ]
