# Generated by Django 2.2.6 on 2020-02-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200130_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_id',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
