# Generated by Django 2.2.6 on 2020-02-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20200203_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
