# Generated by Django 2.2.4 on 2020-01-07 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=30)),
                ('catimg', models.FileField(upload_to='catimg')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.FileField(max_length=50, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desg', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Functionalarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionalarea', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=40)),
                ('indimg', models.FileField(upload_to='indimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(max_length=15)),
                ('jobimg', models.FileField(upload_to='jonimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qulification', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('passport', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=25)),
                ('father_name', models.CharField(max_length=50)),
                ('hobbies', models.CharField(max_length=70)),
                ('languages_known', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15)),
                ('marital_status', models.CharField(choices=[('unmarried', 'Unmarried'), ('married', 'Married')], max_length=25)),
                ('career', models.CharField(max_length=300)),
                ('desired_job_title', models.CharField(max_length=30)),
                ('expect_package', models.CharField(max_length=25)),
                ('desired_shift', models.CharField(choices=[('Day shift', 'Day shift'), ('Night shift', 'Night shift'), ('Rotational shift', 'Rotational shift')], max_length=30)),
                ('desired_location', models.CharField(max_length=50)),
                ('availability_to_join', models.CharField(choices=[('Immediatly', 'Immediatly'), ('Within 15days', 'Within 15days'), ('1 month', '1 month'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months ')], max_length=25)),
                ('university_name', models.CharField(max_length=50)),
                ('year_of_passing', models.DateField()),
                ('percentage', models.CharField(max_length=5)),
                ('skills', models.CharField(max_length=70)),
                ('company_name', models.CharField(max_length=40)),
                ('job_description', models.CharField(max_length=400)),
                ('facebook_account', models.URLField()),
                ('google_account', models.URLField()),
                ('twitter_account', models.URLField()),
                ('linkedin_account', models.URLField()),
                ('pinterest_account', models.URLField()),
                ('instagram_account', models.URLField()),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Designation')),
                ('desired_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Industry')),
                ('desired_job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Jobtype')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Experience')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Qualification')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Createjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=50)),
                ('hiringprocess', models.CharField(choices=[('Face to Face', 'Face to Face'), ('Written Test', 'Written Test'), ('Telephonic', 'Telephonic'), ('Group Discussion', 'Group Discussion'), ('Walk in', 'Walk in')], max_length=50)),
                ('no_of_vac', models.CharField(max_length=25)),
                ('joblocation', models.CharField(max_length=60)),
                ('keyskills', models.CharField(max_length=60)),
                ('yofpass', models.CharField(max_length=40)),
                ('qulmarks', models.CharField(max_length=20)),
                ('languages', models.CharField(max_length=100)),
                ('eligiblefor', models.CharField(choices=[('Male candidates only', 'Male candidates only'), ('Female candidates only', 'Female candidates only'), ('both male and female candidates', 'both male and female candidates')], max_length=40)),
                ('flexiblefor', models.CharField(choices=[('Day shift', 'Day shift'), ('Night shift', 'Night shift'), ('Rotational shift', 'Rotational shift')], max_length=50)),
                ('type_of_company', models.CharField(max_length=30)),
                ('comapnyname', models.CharField(max_length=100)),
                ('cemail', models.CharField(max_length=50)),
                ('cnumber', models.IntegerField()),
                ('altermbl', models.IntegerField()),
                ('website', models.URLField()),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('company_logo', models.FileField(upload_to='logos/')),
                ('interview_location', models.CharField(max_length=100)),
                ('contact_person_role', models.CharField(max_length=25)),
                ('contact_person_name', models.CharField(max_length=25)),
                ('cont_per_ofmail', models.EmailField(max_length=254)),
                ('job_summary', models.CharField(max_length=400)),
                ('responsibilities', models.CharField(max_length=400)),
                ('benifits', models.CharField(max_length=400)),
                ('company_descrption', models.CharField(max_length=300)),
                ('facebook', models.URLField()),
                ('google', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('pinterest', models.URLField()),
                ('instagram', models.URLField()),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Country')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.City')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Designation')),
                ('educationqul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Qualification')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Experience')),
                ('funarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Functionalarea')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Industry')),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Jobtype')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.Package')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewjob.State')),
            ],
        ),
    ]
