# Generated by Django 3.0.2 on 2020-03-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnewjob', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='uuid',
        ),
    ]
