# Generated by Django 2.2.6 on 2020-01-29 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appnewjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='uploadyourpic',
            field=models.FileField(default=datetime.datetime(2020, 1, 29, 7, 43, 53, 458589, tzinfo=utc), upload_to='pics'),
            preserve_default=False,
        ),
    ]
