# Generated by Django 2.2.4 on 2020-01-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewjob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
