# Generated by Django 2.2.6 on 2020-01-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewjob', '0002_resume_uploadyourpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='year_of_passing',
            field=models.CharField(max_length=25),
        ),
    ]
