# Generated by Django 3.0.2 on 2020-03-03 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appnewjob', '0002_remove_resume_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
