# Generated by Django 2.2.6 on 2020-02-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnewjob', '0004_auto_20200204_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createjob',
            name='role',
        ),
    ]
