# Generated by Django 2.2.6 on 2020-03-14 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appnewjob', '0007_auto_20200314_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
